#macro TILE_SIZE sprite_get_width(spr_wall)
#macro CELLS 800 div TILE_SIZE

#macro MOD_BOMB_PROXIMITY 10

#macro BOMB_TIMER_MODIFIER 10
#macro ACTION_TIMER_MODIFIER 10
#macro SPEED_FAST 4
#macro SPEED_SLOW 4

#macro EXPLOSION_EFFECT_TRESHOLD .5
#macro POWERUP_DROP_PERCENTAGE 50

#macro MIN_ACTION_TIMER 10
#macro MAX_ACTION_TIMER 120
#macro MIN_BOMB_TIMER 10
#macro MAX_BOMB_TIMER 120